encoding: utf-8
author: 爱上天涯
name: 天涯阁
url: 个人网站
baseurl: ""
resume_site: /author
github: https://github.com/OnlyLoveTianYa
github_username: OnlyLoveTianYa
FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
  